apiVersion: v1
kind: Pod
metadata:
  name: iperf-server
spec:
  nodeName: wg-demo-worker
  containers:
    - name: iperf3
      image: networkstatic/iperf3
      args: ["-s"]
---
apiVersion: v1
kind: Pod
metadata:
  name: iperf-client
spec:
  nodeName: wg-demo-worker2
  containers:
    - name: iperf3
      image: networkstatic/iperf3
      command: ["sleep", "infinity"]
